package com.careermappro.repositories;

import com.careermappro.entities.LearningPath;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface LearningPathRepository extends JpaRepository<LearningPath, Integer> {

    /**
     * Find all learning paths for a specific user
     */
    List<LearningPath> findByUserId(Integer userId);

    /**
     * Find active learning paths for a specific user
     */
    List<LearningPath> findByUserIdAndStatus(Integer userId, LearningPath.PathStatus status);

    /**
     * Find learning paths for a specific role
     */
    List<LearningPath> findByRoleId(Integer roleId);

    /**
     * Find all learning paths for a user ordered by creation date (most recent first)
     */
    List<LearningPath> findByUserIdOrderByCreatedAtDesc(Integer userId);

    /**
     * Find learning paths by difficulty level
     */
    List<LearningPath> findByDifficulty(LearningPath.Difficulty difficulty);

    /**
     * Find active learning paths for a user ordered by last accessed (most recent first)
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.userId = :userId AND lp.status = 'ACTIVE' ORDER BY lp.lastAccessedAt DESC NULLS LAST")
    List<LearningPath> findActivePathsByUserOrderByLastAccessed(@Param("userId") Integer userId);

    /**
     * Find completed learning paths for a user
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.userId = :userId AND lp.status = 'COMPLETED' ORDER BY lp.completedAt DESC")
    List<LearningPath> findCompletedPathsByUser(@Param("userId") Integer userId);

    /**
     * Find abandoned learning paths for a user
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.userId = :userId AND lp.status = 'ABANDONED' ORDER BY lp.createdAt DESC")
    List<LearningPath> findAbandonedPathsByUser(@Param("userId") Integer userId);

    /**
     * Count total learning paths for a user
     */
    long countByUserId(Integer userId);

    /**
     * Count active learning paths for a user
     */
    long countByUserIdAndStatus(Integer userId, LearningPath.PathStatus status);

    /**
     * Find a specific learning path with optional checks
     */
    Optional<LearningPath> findByPathIdAndUserId(Integer pathId, Integer userId);

    /**
     * Find learning paths generated by a specific AI model
     */
    List<LearningPath> findByGeneratedBy(String generatedBy);

    /**
     * Check if a learning path exists for a user
     */
    boolean existsByPathIdAndUserId(Integer pathId, Integer userId);

    /**
     * Find learning paths for a role with a specific difficulty
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.roleId = :roleId AND lp.difficulty = :difficulty")
    List<LearningPath> findByRoleIdAndDifficulty(@Param("roleId") Integer roleId, @Param("difficulty") LearningPath.Difficulty difficulty);

    /**
     * Find user's paths that haven't been started yet
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.userId = :userId AND lp.startedAt IS NULL ORDER BY lp.createdAt DESC")
    List<LearningPath> findNotStartedPathsByUser(@Param("userId") Integer userId);

    /**
     * Find user's paths that are in progress (started but not completed)
     */
    @Query("SELECT lp FROM LearningPath lp WHERE lp.userId = :userId AND lp.startedAt IS NOT NULL AND lp.completedAt IS NULL ORDER BY lp.lastAccessedAt DESC NULLS LAST")
    List<LearningPath> findInProgressPathsByUser(@Param("userId") Integer userId);
}
