package com.careermappro.repositories;

import com.careermappro.entities.StudyResource;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface StudyResourceRepository extends JpaRepository<StudyResource, Integer> {

    /**
     * Find all resources for a specific step
     */
    List<StudyResource> findByStepId(Integer stepId);

    /**
     * Find resources for a step ordered by relevance score (highest first)
     */
    List<StudyResource> findByStepIdOrderByRelevanceScoreDesc(Integer stepId);

    /**
     * Find resources by type
     */
    List<StudyResource> findByType(StudyResource.ResourceType type);

    /**
     * Find resources by difficulty
     */
    List<StudyResource> findByDifficulty(StudyResource.Difficulty difficulty);

    /**
     * Find resources for a step with specific type
     */
    List<StudyResource> findByStepIdAndType(Integer stepId, StudyResource.ResourceType type);

    /**
     * Find resources for a step with specific difficulty
     */
    List<StudyResource> findByStepIdAndDifficulty(Integer stepId, StudyResource.Difficulty difficulty);

    /**
     * Find resources for a step ordered by creation date (most recent first)
     */
    List<StudyResource> findByStepIdOrderByCreatedAtDesc(Integer stepId);

    /**
     * Find high-quality resources (relevance score above threshold)
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.relevanceScore >= :minScore ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findHighQualityResources(@Param("stepId") Integer stepId, @Param("minScore") java.math.BigDecimal minScore);

    /**
     * Find helpful resources marked by users
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.isHelpful = true ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findHelpfulResources(@Param("stepId") Integer stepId);

    /**
     * Find resources by source
     */
    List<StudyResource> findBySource(String source);

    /**
     * Find resources for a step by source
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.source = :source")
    List<StudyResource> findByStepIdAndSource(@Param("stepId") Integer stepId, @Param("source") String source);

    /**
     * Find resources generated by a specific AI model
     */
    List<StudyResource> findByGeneratedBy(String generatedBy);

    /**
     * Find resources with user ratings
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.userRating IS NOT NULL ORDER BY sr.userRating DESC")
    List<StudyResource> findRatedResources(@Param("stepId") Integer stepId);

    /**
     * Find resources with average time estimates
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.estimatedTimeMinutes IS NOT NULL ORDER BY sr.estimatedTimeMinutes")
    List<StudyResource> findResourcesWithTimeEstimate(@Param("stepId") Integer stepId);

    /**
     * Count resources for a step
     */
    long countByStepId(Integer stepId);

    /**
     * Count resources by type for a step
     */
    long countByStepIdAndType(Integer stepId, StudyResource.ResourceType type);

    /**
     * Find beginner-friendly resources for a step
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.difficulty = 'BEGINNER' ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findBeginnerResources(@Param("stepId") Integer stepId);

    /**
     * Find advanced resources for a step
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.difficulty = 'ADVANCED' ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findAdvancedResources(@Param("stepId") Integer stepId);

    /**
     * Find resources by estimated time range
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.estimatedTimeMinutes BETWEEN :minTime AND :maxTime ORDER BY sr.estimatedTimeMinutes")
    List<StudyResource> findByEstimatedTimeRange(@Param("stepId") Integer stepId, @Param("minTime") Integer minTime, @Param("maxTime") Integer maxTime);

    /**
     * Find resources by author
     */
    List<StudyResource> findByAuthor(String author);

    /**
     * Find resources with minimum rating
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.userRating >= :minRating ORDER BY sr.userRating DESC")
    List<StudyResource> findByMinimumRating(@Param("minRating") Integer minRating);

    /**
     * Find video resources for a step
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.type = 'VIDEO' ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findVideoResources(@Param("stepId") Integer stepId);

    /**
     * Find article resources for a step
     */
    @Query("SELECT sr FROM StudyResource sr WHERE sr.stepId = :stepId AND sr.type = 'ARTICLE' ORDER BY sr.relevanceScore DESC")
    List<StudyResource> findArticleResources(@Param("stepId") Integer stepId);

    /**
     * Check if resource exists for a step
     */
    boolean existsByStepIdAndResourceId(Integer stepId, Integer resourceId);
}
