-- V4: Learning Paths System
-- This migration creates the path-driven learning system that makes the app a "mentor"
-- instead of a passive dashboard. Paths are dynamically generated by OpenAI based on
-- user's role and current skill state.

-- =============================================================================
-- Learning Paths: User-specific curriculum generated by AI
-- =============================================================================

CREATE TABLE IF NOT EXISTS learning_paths (
    path_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    role_id INT NOT NULL,

    -- Path structure
    title VARCHAR(200) NOT NULL,
    description TEXT,
    duration_weeks INT NOT NULL DEFAULT 12,
    difficulty ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT') NOT NULL,

    -- AI generation metadata
    generated_by VARCHAR(50) DEFAULT 'gpt-4o-mini',
    generation_prompt TEXT,

    -- Status
    status ENUM('ACTIVE', 'COMPLETED', 'ABANDONED', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    last_accessed_at TIMESTAMP,

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    INDEX idx_user_status (user_id, status),
    INDEX idx_role (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Path Units: High-level milestones (e.g., "Fundamentals", "Advanced Concepts")
-- =============================================================================

CREATE TABLE IF NOT EXISTS path_units (
    unit_id INT AUTO_INCREMENT PRIMARY KEY,
    path_id INT NOT NULL,

    -- Unit structure
    unit_number INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    estimated_hours INT,

    -- Status tracking
    status ENUM('LOCKED', 'AVAILABLE', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'LOCKED',

    -- Timestamps
    unlocked_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,

    -- Constraints
    FOREIGN KEY (path_id) REFERENCES learning_paths(path_id) ON DELETE CASCADE,
    UNIQUE KEY unique_path_unit (path_id, unit_number),
    INDEX idx_path_status (path_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Path Steps: Individual skills to master within a unit
-- =============================================================================

CREATE TABLE IF NOT EXISTS path_steps (
    step_id INT AUTO_INCREMENT PRIMARY KEY,
    unit_id INT NOT NULL,
    skill_id INT NOT NULL,

    -- Step structure
    step_number INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    learning_objectives TEXT, -- What you'll learn
    success_criteria TEXT,    -- How we know you've mastered it

    -- Status tracking
    status ENUM('LOCKED', 'AVAILABLE', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'LOCKED',

    -- Progress tracking
    confidence_target DECIMAL(3,2) DEFAULT 0.70, -- Target confidence to complete step
    evidence_count INT DEFAULT 0,                 -- Number of evidence items submitted
    attempts INT DEFAULT 0,                       -- Number of quiz attempts

    -- Timestamps
    unlocked_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,

    -- Constraints
    FOREIGN KEY (unit_id) REFERENCES path_units(unit_id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skill_nodes(skill_node_id),
    UNIQUE KEY unique_unit_step (unit_id, step_number),
    INDEX idx_unit_status (unit_id, status),
    INDEX idx_skill (skill_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Study Resources: AI-curated resources for each step
-- =============================================================================

CREATE TABLE IF NOT EXISTS study_resources (
    resource_id INT AUTO_INCREMENT PRIMARY KEY,
    step_id INT NOT NULL,

    -- Resource details
    type ENUM('ARTICLE', 'VIDEO', 'TUTORIAL', 'DOCUMENTATION', 'COURSE', 'PRACTICE') NOT NULL,
    title VARCHAR(300) NOT NULL,
    url VARCHAR(500) NOT NULL,
    description TEXT,
    estimated_time_minutes INT,
    difficulty ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL,

    -- Metadata
    source VARCHAR(100), -- e.g., "MDN", "YouTube", "Coursera"
    author VARCHAR(200),
    relevance_score DECIMAL(3,2) DEFAULT 0.80, -- AI's confidence in relevance

    -- Generated by AI
    generated_by VARCHAR(50) DEFAULT 'gpt-4o-mini',

    -- User feedback
    is_helpful BOOLEAN,
    user_rating INT, -- 1-5 stars

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    FOREIGN KEY (step_id) REFERENCES path_steps(step_id) ON DELETE CASCADE,
    INDEX idx_step_type (step_id, type),
    INDEX idx_relevance (relevance_score DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Path Progress: Detailed tracking of user journey through path
-- =============================================================================

CREATE TABLE IF NOT EXISTS path_progress (
    progress_id INT AUTO_INCREMENT PRIMARY KEY,
    path_id INT NOT NULL,
    user_id INT NOT NULL,

    -- Current position
    current_unit_id INT,
    current_step_id INT,

    -- Progress metrics
    total_units INT NOT NULL DEFAULT 0,
    completed_units INT NOT NULL DEFAULT 0,
    total_steps INT NOT NULL DEFAULT 0,
    completed_steps INT NOT NULL DEFAULT 0,

    -- Engagement metrics
    total_time_minutes INT NOT NULL DEFAULT 0,
    evidence_submitted INT NOT NULL DEFAULT 0,
    quizzes_completed INT NOT NULL DEFAULT 0,

    -- Calculated progress
    overall_progress DECIMAL(5,2) DEFAULT 0.00, -- 0.00 to 100.00

    -- Timestamps
    last_activity_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints
    FOREIGN KEY (path_id) REFERENCES learning_paths(path_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (current_unit_id) REFERENCES path_units(unit_id) ON DELETE SET NULL,
    FOREIGN KEY (current_step_id) REFERENCES path_steps(step_id) ON DELETE SET NULL,
    UNIQUE KEY unique_user_path (user_id, path_id),
    INDEX idx_user (user_id),
    INDEX idx_progress (overall_progress)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Path Activities: Event log for path-related actions
-- =============================================================================

CREATE TABLE IF NOT EXISTS path_activities (
    activity_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    path_id INT NOT NULL,
    step_id INT,

    -- Activity details
    activity_type ENUM(
        'PATH_STARTED',
        'UNIT_UNLOCKED',
        'UNIT_COMPLETED',
        'STEP_UNLOCKED',
        'STEP_STARTED',
        'STEP_COMPLETED',
        'EVIDENCE_SUBMITTED',
        'QUIZ_TAKEN',
        'RESOURCE_ACCESSED',
        'MILESTONE_REACHED'
    ) NOT NULL,

    -- Activity context
    description TEXT,
    metadata JSON, -- Additional context (e.g., quiz score, evidence ID)

    -- Timestamps
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (path_id) REFERENCES learning_paths(path_id) ON DELETE CASCADE,
    FOREIGN KEY (step_id) REFERENCES path_steps(step_id) ON DELETE SET NULL,
    INDEX idx_user_time (user_id, created_at DESC),
    INDEX idx_path_time (path_id, created_at DESC),
    INDEX idx_type (activity_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================================
-- Initial Data: Placeholder for testing (will be replaced by AI generation)
-- =============================================================================

-- This will be replaced by the PathGenerationService
-- For now, just create the schema
